### ISSUE TITLE
Storybook doesn't use latest version of Vanilla

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/react-components#109]
Even that project has Vanilla as dependency in package.json and is kept up to date with renovate the styles used by storybook are actually coming from hardcoded old version of Vanilla.

This makes impossible to make sure that the react component work and look correctly with latest version of vanilla.

https://github.com/canonical-web-and-design/react-components/blob/1527b939a5a12935ee274c3800c9529d3669d70c/.storybook/preview-head.html#L1-L4

### Expected

Storybook should include the same version of Vanilla as is used in dependencies.

**Comment by huwshimi** [comment]
Fixed in https://github.com/canonical-web-and-design/react-components/pull/196
