### ISSUE TITLE
MainTable caption shouldn't have a negative margin

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/react-components#126]
The negative margin on the `caption` element in the table causes it to move into the header if there is no content in the table.

![Screen Shot 2020-05-13 at 2 04 17 PM](https://user-images.githubusercontent.com/532033/81965460-4e276a00-95d5-11ea-9ad7-c94771b44025.png)

https://github.com/canonical-web-and-design/react-components/blob/3ed7f3f15613eae14071136353e9f1c6828f1c24/src/components/MainTable/MainTable.scss#L7

**Comment by bartaz** [comment]
Already fixed. There are no custom CSS in react-components anymore.
