### ISSUE TITLE
Investigate UX tools

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#13]
Take a look at whether these components could be used with https://www.framer.com/ and Sketch.

**Comment by huwshimi** [comment]
This could be helpful: https://blog.zeplin.io/connect-zeplin-with-react-and-storybook-3895b215009f

**Comment by lyubomir-popov** [comment]
We don't use framer and we're hoping to move from sketch to figma, so I don't think this would fit in the design pipeline as it currently is.
