### ISSUE TITLE
No way of adding a data attr to table cells

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/react-components#132]
As part of our testing, we would like to provide or automatically assign a `data-test` attr to a table cell. This is currently not possible with the current component.

**Comment by huwshimi** [comment]
@anthonydillon you can pass additional html attributes to the cell object and they will be passed to the cell.

So you could do something like this:

```javascript 
{
    content: last_login,
    "data-date": last_login
}
```

And the cell will become something like:

`<td role="gridcell" data-date="2020-01-01">2020-01-01</td>`

We need to document that this can be done.

**Comment by anthonydillon** [comment]
Ah cool thanks.
