### ISSUE TITLE
Build Navigation component

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#134]
- Default
- Dark
- Full-width
- Sub navigation

**Comment by Caleb-Ellis** [comment]
Putting this back into the backlog for now - got pretty tricky trying to align the Header component in maas-ui with a TS Navigation component in react-components. I have half-finished branches ready to pick up again when this comes back into an iteration.

**Comment by cristinadresch** [comment]
@anthonydillon we were wondering why you marked this as high? do you know of any places that would use this?

**Comment by anthonydillon** [comment]
Sorry, I must have missed this. Any web style project using react needs this, such as 360.
