### ISSUE TITLE
Specify when to use / when not to use dense form elements

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#136]
[Mini-spec](https://docs.google.com/document/d/10iVKaMK6ncD1QYVUvo0Thsp1dnA69wFjepgIP4fnraM/edit#) ready for review.

**Comment by bartaz** [comment]
We need to define how to mix dense and not-dense inputs on UX level.

**Comment by anthonydillon** [comment]
Sounds like there is a discussion to be had on this topic so moving back to WG.

**Comment by bartaz** [comment]
For context:

Currently in Vanilla we have an option for 'dense' form elements https://vanillaframework.io/docs/base/forms#dense-form-elements which are supposed to be used "when vertical space is limited".

The way it's implemented allows to change the size of the field per field rather than for the whole form.

We need a UX/design decision if we ever want to mix dense and non dense fields, when to use either of them, so we can reflect that in React implementation.

**Comment by lyubomir-popov** [comment]
THe question to ask is why do we hav two versions and in what contexts / onm which elements would that make sense.
For example, in elements with fixed height, or elements that would become ifferent in height if a full button is inserted, e.g. a table row or a toolbar

**Comment by wgx** [comment]
@bartaz @lyubomir-popov 

> We need a UX/design decision if we ever want to mix dense and non dense fields, when to use either of them, so we can reflect that in React implementation.

I'm trying to think of a situation where we'd want to mix dense and non-dense in the same form, and I can't come up with a viable use. If space is constrained, use dense, if not, prefer normal.

**Comment by lyubomir-popov** [comment]
I think dense inputs should be limited to inside tables, or inside tiny toolbars.

**Comment by wgx** [comment]
As discussed in Design Assembly, this poses no usability issues, so I'm bowing out of the UX on this one. 

Remaining questions around dense vs non-dense are to do with spacing, vertical rythm, etc - so would be best to have visual designer(s) do a mini-workshop on the rules for the use of each type.

**Comment by clagom** [comment]
WG: @wgx had a look from UX perspective and the conclusion is that this is more of a visual guideline to provide from visual/UI perspective when and where to use the dense version.

**Comment by clagom** [comment]
WG: we are going to disscuss use cases about the adoption of a dense form component during the next design assembly.

**Comment by lyubomir-popov** [comment]
Link to a figma file t ocollect the audit of current usage: https://www.figma.com/file/ReJnCt8sjwKxoBjQJ5qqXg/Dense-forms-audit?node-id=0%3A1

**Comment by lyubomir-popov** [comment]
This issue is in the wg ui/ux pipeline, and the discussion on it is purely design related. Should we change the title to reflect this?

**Comment by danielmutis** [comment]
I have read the spec and it makes sense to me. It seems that the scenarios of when to use and when not to are clear and don't see any issues with it.
