### ISSUE TITLE
Storybook console error: React no likey camelCase for prop names

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#158]
<img width="743" alt="Screenshot 2020-06-22 at 11 43 57" src="https://user-images.githubusercontent.com/505570/85280912-0243cc80-b481-11ea-8f83-288a75f3c57b.png">

**Comment by huwshimi** [comment]
This is a component prop that has somehow made its way onto a DOM node, probably because of a spread.

**Comment by Caleb-Ellis** [comment]
@huwshimi I can't seem to replicate this - can you?

**Comment by huwshimi** [comment]
> @huwshimi I can't seem to replicate this - can you?

No, I think it was probably a bit of a red herring to begin with.
