### ISSUE TITLE
Running `yarn test` formats tsconfig.json

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#203]
Whenever I run `yarn test`, the tsconfig.json file is reformatted?

<img width="586" alt="Screenshot 2020-08-05 at 15 45 41" src="https://user-images.githubusercontent.com/505570/89427246-f3fcf780-d732-11ea-8e30-4fe9babba8dd.png">

**Comment by squidsoup** [comment]
Dup of #199
