### ISSUE TITLE
[Storybook] Code examples appear incorrect?

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#254]
In Storybook, the code snippets for each component appear incorrect?

Shouldn't this example below show something like; `<Spinner prop={foo} />`

<img width="1199" alt="Screenshot 2020-08-26 at 10 11 09" src="https://user-images.githubusercontent.com/505570/91285224-d85e9d00-e784-11ea-8729-7b5905cd15c7.png">

**Comment by huwshimi** [comment]
This appears to be this bug: https://github.com/storybookjs/storybook/issues/11542

**Comment by sowasred2012** [comment]
Closing: this was fixed in [storybook 6.3.0](https://github.com/storybookjs/storybook/releases/tag/v6.3.0), which was updated to in this project two days ago by [this dependency update](https://github.com/canonical-web-and-design/react-components/commit/881f1546fd8ab0170282b2f878ba5c84cd0e610d).
