### ISSUE TITLE
Update checkbox and radio buttons

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#259]
Update to the latest Vanilla structure for radio buttons and checkboxes.

This could mean a new component (or two) instead of part of Input as it is now:

https://vanillaframework.io/docs/base/forms#radio-button

https://vanillaframework.io/docs/base/forms#checkbox

**Comment by bartaz** [comment]
The scope should include:

- adding react equvalents of `p-checkbox` and `p-radio`
- add `is-table-header` option to checkboxes to align them in table headings

Open questions:

- should we (and can we) remove the checkbox/radio types from Input component
