### ISSUE TITLE
`yarn build-watch` doesn't rebuild on file changes

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/react-components#261]
I'm not sure if is my setup or some bug, but for me `yarn build-watch` doesn't rebuild files (or doesn't detect changes).
It starts:

<img width="749" alt="Screenshot 2020-09-04 at 10 08 21" src="https://user-images.githubusercontent.com/83575/92216477-9e814b00-ee96-11ea-84c6-9643d74d0eb4.png">

but that's all, nothing changes when I edit files.

Running directly on macOS machine (not via multipass).

**Comment by Caleb-Ellis** [comment]
@bartaz is this still not working for you? It seems to work on my machine

![2021-07-09_11-53](https://user-images.githubusercontent.com/25733845/125011712-53cef180-e0ac-11eb-888d-1b40d1afeadf.png)

**Comment by bartaz** [comment]
@Caleb-Ellis Oh, I'll double check then.

**Comment by bartaz** [comment]
Seems to be working.
