### ISSUE TITLE
Errors when adding to a project

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/react-components#262]
I added this repo to my project with `yarn add @canonical/react-components --save-exact`.

I imported the component like so:

```
import { Select } from "@canonical/react-components";
```

I then ran the project using the [dotrun snap](https://github.com/canonical-web-and-design/dotrun) and got the following output in the terminal:

https://pastebin.canonical.com/p/XFN7dPtR3H/

**Comment by squidsoup** [comment]
Hi @steverydz, you need [sass-loader](https://github.com/webpack-contrib/sass-loader)
