### ISSUE TITLE
SearchBox broken in 0.10.0

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#281]
The updated SearchBox has some styling issues:

<img width="997" alt="Screen Shot 2020-09-21 at 9 33 32 am" src="https://user-images.githubusercontent.com/361637/93724799-92fb8700-fbed-11ea-83d5-3e937276dd8e.png">

Also the change to using forwardRef has made it so tests can't do `wrapper.find("SearchBox")` any more (returns nothing).

Not sure if something can be done to make that work again. I wonder if there's something here that might help:
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

**Comment by huwshimi** [comment]
Hi @barrymcgee I wonder if you wouldn't mind taking a look at this as you've been updating the SearchBox lately?

It's possible we just need to update things on the maas-ui side...

**Comment by huwshimi** [comment]
@barrymcgee any thoughts about the forwardRef part of this?

**Comment by barrymcgee** [comment]
What test is it failing?

**Comment by squidsoup** [comment]
> What test is it failing?

Any enzyme test that uses `wrapper.find("SearchBox")`

**Comment by huwshimi** [comment]
Turns out we just need to set the display name so it shows up as SearchBox instead of ForwardRef.
