### ISSUE TITLE
Auto-positioned contextual menu should ensure it is within the window bounds

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#299]
On resize, popover should ensure it is within the window bounds:

![image](https://user-images.githubusercontent.com/2741678/94436614-90240780-0194-11eb-87c5-c6a4462bffc7.png)

_Originally posted by @lyubomir-popov in https://github.com/canonical-web-and-design/MAAS-squad/issues/2079#issuecomment-699997242_

**Comment by huwshimi** [comment]
Added in this PR: https://github.com/canonical-web-and-design/react-components/pull/275.
