### ISSUE TITLE
CSSTransitons in ContextulMenu are not compatible with Strict Mode React projects

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#320]
This console error is thrown when including SearchAndFilter in a clean sandbox

<img width="1197" alt="Screenshot 2020-10-29 at 14 54 15" src="https://user-images.githubusercontent.com/505570/97590631-ba1c5400-19f6-11eb-9cc7-e8bb098de97a.png">

**Comment by huwshimi** [comment]
@barrymcgee I wonder if you wouldn't mind taking a look at this one? CSSTransitons was only added to support the search and filter animations. Probably there's a better way of doing that, maybe one that doesn't require a dependency.
