### ISSUE TITLE
Investigate replacing nanoid with Date.now()

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#325]
It's possible that we could drop the nanoid dep in favour of a utility that returns `Date.now()` (maybe adding a random string to avoid any chance of a conflict).

**Comment by petermakowski** [comment]
I believe this is no longer relevant/we should rename this issue as React introduced their own `useId` hook: https://github.com/facebook/react/pull/22644

**Comment by petermakowski** [comment]
Closing in favour of https://github.com/canonical-web-and-design/react-components/issues/776
