### ISSUE TITLE
Percy Test GH Action fails

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/react-components#344]
I noticed that 'Percy Test' GH Action returns failed result, but screenshots seem to be taken and processed.

In the action log there are some errors about using deprecated commands:

<img width="1484" alt="Screenshot 2020-11-25 at 08 26 49" src="https://user-images.githubusercontent.com/83575/100195771-2015d180-2ef8-11eb-9625-41a254084632.png">

Not sure if it's an issue on our side or percy action?

But we also discussed moving running Percy to Circle CI, so maybe not worth looking into too much.

**Comment by huwshimi** [comment]
I've landed all the dep updates which has fixed this issue.
