### ISSUE TITLE
Tooltips don't work on disabled buttons

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#359]
This happens on Chrome but not on Firefox. If a button is disabled, all events on it are disabled, including triggering the tooltip on hover.

**Comment by sowasred2012** [comment]
Added https://github.com/canonical-web-and-design/vanilla-framework/issues/2180 as a dependency, as it's addressing the same thing in Vanilla and we're discussing whether we even want to support tooltips on disabled elements.

**Comment by sowasred2012** [comment]
Closing this one - we decided to advise against using tooltips on disabled elements, the argument being it should be clear to the user why it's disabled with the need for them to interact with an element first to get the information: https://github.com/canonical-web-and-design/vanilla-framework/pull/3689

We also created an issue to discuss whether we need a new pattern that covers the use case of needing to somehow indicate why an element is disabled: https://github.com/canonical-web-and-design/vanilla-framework/issues/3690
