### ISSUE TITLE
Update Code component to latest Vanilla design

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#372]
See the breaking changes: https://github.com/canonical-web-and-design/vanilla-framework/releases/v2.22.0

**Comment by bartaz** [comment]
The 'breaking' changes are purely visual, so the old component should still work. Obviously removal of copy button will affect UIs that in some way depended on it.

The new Code Snippet component was added (and we still develop features for it), so eventually I guess we would need to build React `CodeSnippet` and deprecate the `Code`.

**Comment by bartaz** [comment]
The `p-code--copyable` and `p-code--numbered` are deprecated in Vanilla.
We should update the Code component to use CodeSnippet instead (as a proxy/alias). In longer term Code component should be deprecated and removed.
