### ISSUE TITLE
README is unhelpful to contributors

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#38]
The README tells me how to consume this lib but not how to contribute to it, explaining Storybook, how to run it, etc

**Comment by steverydz** [comment]
:+1: 

We should probably have a `CONTRIBUTING.md` doc

**Comment by huwshimi** [comment]
I did make a start on this, but it needs to be added to the project: https://github.com/canonical-web-and-design/react-components/issues/8

Feel free to make suggestions on what other details would be helpful.
