### ISSUE TITLE
Add Accordion option to have multiple open sections

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/react-components#399]
In the Juju Dashboard we require that multiple accordion sections be open at once and be initially rendered opened:

![Screen Shot 2021-03-09 at 2 08 11 PM](https://user-images.githubusercontent.com/532033/110531254-f7010180-80e0-11eb-8871-4cafd4e82fa3.png)

**Comment by hatched** [comment]
To support this we also probably want to update the [expanded prop](https://github.com/canonical-web-and-design/react-components/blob/master/src/components/Accordion/Accordion.tsx#L82) to take an `array` of segments not just a single one.

**Comment by hatched** [comment]
I'd like to propose a new prop `independentSegments` which will allow each segment to act independent of the others so that they can be opened and closed independently.

**Comment by bartaz** [comment]
Is it still 'accordion', or simply separate collapsable sections? Or maybe multiple single-section accordions?

Also, Vanilla accordion has the whole "heading" section clickable - in the screenshots it seems there are also some chips there next to "4 Local applications", etc. Are they interactive as well? This seems bit more than accordion provides.

**Comment by barrymcgee** [comment]
@bartaz The chips in the Accordion heading have been descoped for now after I raised with the design team that the Accordion component does not support that.

**Comment by hatched** [comment]
> Is it still 'accordion', or simply separate collapsable sections? Or maybe multiple single-section accordions?

This is a great idea :) I think we'll investigate this before implementing any changes to this component

**Comment by hatched** [comment]
We have instead created a separate component to handle the unique usecase that we have. If others end up in the same boat we can look at making these changes upstream but for now I'll close this.
