### ISSUE TITLE
MainTable doesn't allow for double rows

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/react-components#40]
The `MainTable` component currently only allows single rows. In MAAS we use double rows in a lot of places (see screenshot) and need the flexibility to use the component in this way.

<img width="1419" alt="Screen Shot 2019-11-21 at 12 16 51 pm" src="https://user-images.githubusercontent.com/361637/69291961-d8ab9400-0c58-11ea-8dae-5a3c7dbc40aa.png">

**Comment by Caleb-Ellis** [comment]
@steverydz I thought you could pass anything to the `content` param of a cell? What's preventing just having something like:
``` js
content: (
  <div className="double-row">
    <div className="double-row__first-row">
      ...
    </div>
    <div className="double-row__second-row">
      ...
    </div>
  </div>
),
```

Or do you mean specifically this sort of functionality should be baked in to the component?

**Comment by steverydz** [comment]
@Caleb-Ellis oh, it wasn't clear that was an option. I'll give that a try.

**Comment by steverydz** [comment]
I'm going to close this as we can pass components into the table cells
