### ISSUE TITLE
`highlightSubString` util needs to be more resilient

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/react-components#477]
related: https://github.com/canonical-web-and-design/jaas-dashboard/issues/1013

If the `highlightSubString` util is called with invalid values then it throws and breaks the application. It should be more resilient as it's is typically a downstream change that's not easy to fix on the client side.

**Comment by bartaz** [comment]
@hatched Is this related to a particular component? I'm not sure whats the context of `highlightSubString` util.

**Comment by hatched** [comment]
Sorry @bartaz I was actually actively working on this fix.
