### ISSUE TITLE
Button generic in Props definition is incorrect

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/react-components#564]
The `Button` component accepts a generic `P` for cases where e.g. the `Button` is actually an `a` instead and so needs a different set of props. However the type expression `(Omit<ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> | P)` requires that any props in the generic must also be a normal button prop, which isn't very useful.

**Comment by bartaz** [comment]
@Caleb-Ellis @huwshimi Can you give bit more context to this or any pointers how it should be fixed? Current description seems quite vague for us not working with TS on daily basis.

**Comment by Caleb-Ellis** [comment]
@bartaz @carkod Sorry, that was a pretty incomprehensible issue description.

The problem I was having was that trying to use the generic `P` when using a button, e.g:
``` typescript
<Button<{ extraProp: string }>
  extraProp="value"
>
  Button text
</Button>
```

...was giving an error saying that `extraProp` doesn't exist on `ButtonHTMLAttributes<HTMLButtonElement>`. The only way to make it work was for `P` to be a superset of `ButtonHTMLAttributes<HTMLButtonElement>`, so it needed all button props *and* the extra props. My assumption was because there was a problem with the type expression in the `Button` component `(Omit<ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> | P)` but looking at it again it seems fine.

Anyway I don't seem to be getting that error anymore so either I have no idea what I'm talking about or maybe it was a TS bug that was fixed? Either way I think it's safe to close this.
