### ISSUE TITLE
[Select] Options should accept null

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#570]
The optional [`Options` prop](https://github.com/canonical-web-and-design/react-components/blob/master/src/components/Select/Select.tsx#L56) should accept `null`.

**Comment by hatched** [comment]
Why? :)

When making issues like this we should try to answer at least 2 of the W's, What and Why, to encourage discussion (if anyone feels it necessary).

**Comment by huwshimi** [comment]
Ah right sorry, this is a constantly occurring issue, so I presumed (foolishly) that most people would have come across it.

When generating props (like for the options) often methods or selectors will return `null` when there are no values, however, while the prop is optional it accepts the values or undefined, but not `null` so you end up with an error:

```bash
Type 'Option[] | null' is not assignable to type 'Option[] | undefined'.
Type 'null' is not assignable to type 'Option[] | undefined'.
```
