### ISSUE TITLE
Spinner is missing an aria role

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/react-components#590]
It would be nice to add an aria role to the Spinner component. It would make it more accessible and also make it easier to test with RTL.

**Comment by huwshimi** [comment]
We should also add a spread to the wrapping `span` element so these kinds of attributes can be added as needed by component consumers.

**Comment by bartaz** [comment]
Scope:
- investigate what aria attributes to add to Spinner
- add them in react component
