### ISSUE TITLE
Add a way to achieve a table cell which spans the height of several rows

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/react-components#595]
There doesn't appear to be away to have a table cell span the height of several rows which would require the first cell of the first cell to have the `rowspan` attribute and then omit that cell from the following rows.

See screenshot for an example:

<img width="1401" alt="Screenshot 2021-09-15 at 10 53 38" src="https://user-images.githubusercontent.com/501889/133412882-b42e2465-065a-4ac4-ae49-8041ff066988.png">

**Comment by bartaz** [comment]
@steverydz Is this using `MainTable` component or `ModularTable`? I guess neither may have support for that right now, but it may be easier to achieve with `ModularTable` as it has more flexible React table hooks internal implementation.  `MainTable` has API that uses tabular data directly, to it may be harder to achieve there in intuitive way.

**Comment by steverydz** [comment]
@bartaz I tried both but was very complicated. Much easier to use a regular `<table>` in my situation.

**Comment by bartaz** [comment]
@steverydz Yes, I guess the easiest workaround is to use `<table>` and generate rows and cells "manually".
While not documented, I believe there are `Table` `TableRow` `TableCell` components that you could use for that, but they are practically the same as using HTML equivalents directly.

OK. We will have a look on how to add rowSpan to either ModularTable and/or MainTable components.

**Comment by huwshimi** [comment]
@steverydz you can pass arbitrary HTML attributes to rows and columns with `MainTable` like this:

```jsx
  rows={[
    {
      columns: [
        {
          content: 'Expert delivery of an Ubuntu OpenStack cloud',
          role: 'rowheader',
          rowspan: 2,
        },
        ...
```

Here's a codepen of it in action:

https://codepen.io/huwshimi/pen/BaZmOXb?editors=1111

Is that what you need?

**Comment by bartaz** [comment]
@huwshimi Great thanks! I was expecting the `rows` need to have exactly the same number of cells in data. But I guess it's simply 1:1 relation between the `rows` data and HTML of the table?

BTW, how does react-components end up in CDN? Is this something automatic?

**Comment by huwshimi** [comment]
> @huwshimi Great thanks! I was expecting the `rows` need to have exactly the same number of cells in data. But I guess it's simply 1:1 relation between the `rows` data and HTML of the table?

That's right, the only time this differs is when it's an expanding table and needs to add an extra column.

> 
> BTW, how does react-components end up in CDN? Is this something automatic?

Yeah it's an automatic service that pulls the package from NPM. If you're using codepen and add a package from NPM then it'll insert the import automatically.

**Comment by steverydz** [comment]
@huwshimi yes that does the trick - thanks!
