### ISSUE TITLE
Storybook should be deployed to Github pages

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/react-components#63]
We would then have a permanent, online link to reference docs.

https://storybook.js.org/docs/basics/exporting-storybook/#deploying-to-github-pages

**Comment by huwshimi** [comment]
We already do! https://canonical-web-and-design.github.io/react-components/

**Comment by barrymcgee** [comment]
Oh cool, I've added that link to the top of the repo homepage.
