### ISSUE TITLE
Skip Cypress for most CI tasks

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/react-components#88]
When running the CI tasks we should skip the Cypress binary install to speed up the setup for all tasks except the integration tests.

https://docs.cypress.io/guides/getting-started/installing-cypress.html#Skipping-installation

**Comment by huwshimi** [comment]
It doesn't look like we've done this.

**Comment by Caleb-Ellis** [comment]
@huwshimi I thought you did do this? My mistake. I'm just going through the issue list now and closing all the "already dones" and "not going to dos"

**Comment by huwshimi** [comment]
@Caleb-Ellis Ah, I did do the same change on maas-ui!
